### ISSUE TITLE
Contribution.md for Build and Use Question on --legacy-peer-deps

### ISSUE THREAD

**Issue by dunhampa** [viqueen/confluence-static-site#47]
### Question for following the steps in Contribution.md:

Question: is `npm install --legacy-peer-deps` the correct install step for `npm install'? 

---
### Details

My steps:
 
✅  Successfully ran `nvm install`
❌  Running `npm install` 

Returns error with fix of:
```
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution`
```
Complete error in screenshot

Running
```
npm install --legacy-peer-deps
```
does seem to install correctly.

---

**❓  Is this correct way for install to include --legacy-peer-deps?**

---

### Steps and Error:

Install with intermediate error:
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/5845872/233790645-674545f8-87b8-4693-a7dd-1e6330de3c0c.png">

**Comment by viqueen** [comment]
@dunhampa 

that is correct, if we are to keep using `npm` we will need to run with `--legacy-peer-deps`.
for that matter I had switched to using `yarn` in place of `npm` and simply forgot to update the docs here .

see changes in https://github.com/viqueen/confluence-static-site/pull/48

**Comment by dunhampa** [comment]
This worked for me. 

I also verified I was able to use cli after building.  I had run into a snag on this when using the npm documentation.

Thanks for update!
