### ISSUE TITLE
Add open source license to this project

### ISSUE THREAD

**Issue by kelchm** [viqueen/confluence-static-site#50]
Awesome work on the confluence static site generator @viqueen!

I wanted to reach out to see if you would consider adding a license file to the project. This would be consistent with good community practices and would allow others to build upon your work with a clear set of rules for what is permissible.

To ensure maximum compatibility with other software projects, consider the use of the [MIT license](https://opensource.org/licenses/MIT). Of course, remember to replace the copyright statement with your own copyright information.

**Comment by viqueen** [comment]
Hei hei @kelchm 
Thanks for the support !

Yes absolutely, a missing license file is just an oversight from my part, all my node packages are released under [Apache-2.0 license](https://www.apache.org/licenses/LICENSE-2.0) .
I'll get on that at some point this week.

**Comment by viqueen** [comment]
Hei hei @kelchm 
I've released 1.0.0 with Apache-2.0 instead of MIT ( ... I understand they are "somewhat" the same 😄 ) just to align with the rest of my packages.
